server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
ribbon:
  eureka:
    enabled: true